package uk.co.clockworktitan.controller;

import org.json.simple.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import uk.co.clockworktitan.DefaultOutgoingsRepository;
import uk.co.clockworktitan.OutgoingsTypeRepository;
import uk.co.clockworktitan.model.AffordabilityCase;
import uk.co.clockworktitan.model.DefaultOutgoings;
import uk.co.clockworktitan.model.OutgoingsType;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/DefaultOutgoings") // This means URL's start with /demo (after Application path)


public class DefaultOutgoingsController {
    @Autowired // This means to get the bean called OutgoingsTypeRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private DefaultOutgoingsRepository DefaultOutgoingsRepository;


    @GetMapping(path="/all")
    public @ResponseBody Iterable<DefaultOutgoings> getAllDefaultOutgoings() {
        // This returns a JSON or XML with the OutgoingsTypes
        return DefaultOutgoingsRepository.findAll();
    }


}
